# Generated by Django 6.0.5 on 2026-05-08 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISessionFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation_mode', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('crosswalk', 'Crosswalk')], max_length=20)),
                ('frame_timestamp', models.DateTimeField(auto_now_add=True)),
                ('detected_objects', models.JSONField(blank=True, default=list)),
                ('crowd_density', models.FloatField(default=0.0)),
                ('visibility_score', models.FloatField(default=1.0)),
                ('actionable_guidance', models.TextField(blank=True)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_frames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMemoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned_routes', models.JSONField(blank=True, default=list)),
                ('dangerous_spots', models.JSONField(blank=True, default=list)),
                ('preferred_walking_speed', models.FloatField(default=1.0)),
                ('preferred_walking_style', models.CharField(blank=True, max_length=100)),
                ('frequent_transit_patterns', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
